<?php
/*
 *  Request price form
 */
?>
<form class="form contact"
      action="<?= $block->getFormAction(); ?>"
      id="request-price-form"
      method="post"
      data-hasrequired="<?= __('* Required Fields') ?>"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">
        <legend class="legend"><span>Please write your requested price</span></legend><br />
        <div class="field name required">
            <label class="label" for="customer_name"><span><?= __('Name') ?></span></label>
            <div class="control">
                <input name="name" id="customer_name" title="<?= __('Name') ?>" class="input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>
        <div class="field email required">
            <label class="label" for="request_email"><span><?= __('Email') ?></span></label>
            <div class="control">
                <input name="request_email" id="request_email" title="<?= __('Email') ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
            </div>
        </div>
        <div class="field comment required">
            <label class="label" for="comment"><span><?= __('Your can ask for price and write additional text here') ?></span></label>
            <div class="control">
                <textarea name="comment" id="comment" title="<?= __('Your can ask for price and write additional text here') ?>" class="input-text" cols="5" rows="3" data-validate="{required:true}"></textarea>
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <input type="hidden" name="product_sku" id="product_sku" value="<?= $block->getCurrentProduct()->getSku(); ?>" />
        </div>
    </div>
</form>
